spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: allan1005
    url: jdbc:mysql://47.106.89.102:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  redis:
    host: 10.16.69.68
    port: 6379
  jpa:
    show-sql: true
girl: 18
