spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: allan1005
    url: jdbc:mysql://47.106.89.102:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  redis:
    host: 127.0.0.1
    port: 6379
